# content/services.yaml

eyebrow: "Everything you need"
title: "No server? No problem."
subtitle: >
    Lorem ipsum, dolor sit amet consectetur adipisicing elit. Maiores impedit
    perferendis suscipit eaque, iste dolor cupiditate blanditiis.

screenshots:
    src: "images/dark-project-app-screenshot.png"
    width: 2432
    height: 1442
    alt: "App screenshot"

features:
    - icon: "images/icons/cloud-arrow-up.svg"
      title: "Push to deploy."
      text: "Lorem ipsum, dolor sit amet consectetur adipisicing elit aute id magna."
    - icon: "images/icons/lock-closed.svg"
      title: "SSL certificates."
      text: "Anim aute id magna aliqua ad ad non deserunt sunt. Qui irure qui lorem cupidatat commodo."
    - icon: "images/icons/arrow-path.svg"
      title: "Simple queues."
      text: "Ac tincidunt sapien vehicula erat auctor pellentesque rhoncus."
    - icon: "images/icons/finger-print.svg"
      title: "Advanced security."
      text: "Lorem ipsum, dolor sit amet consectetur adipisicing elit aute id magna."
    - icon: "images/icons/cog-6-tooth.svg"
      title: "Powerful API."
      text: "Anim aute id magna aliqua ad ad non deserunt sunt. Qui irure qui lorem cupidatat commodo."
    - icon: "images/icons/server-stack.svg"
      title: "Database backups."
      text: "Ac tincidunt sapien vehicula erat auctor pellentesque rhoncus."
