# content/services.yaml

eyebrow: "Tout ce dont vous avez besoin"
title: "Un développement sur mesure"
subtitle: >
    De la conception à la mise en ligne, j’accompagne mes clients pour créer des sites
    et applications modernes, performants et sécurisés.

screenshots:
    src: "images/dark-project-app-screenshot.png"
    width: 2432
    height: 1442
    alt: "Capture d’un tableau de bord web moderne"

features:
    - icon: "images/icons/cloud-arrow-up.svg"
      title: "Mise en ligne simplifiée."
      text: "Je prends en charge le déploiement et l’hébergement afin que vos outils soient accessibles en toute simplicité."

    - icon: "images/icons/lock-closed.svg"
      title: "Sécurité renforcée."
      text: "Protection des données, certificats SSL et bonnes pratiques de cybersécurité intégrées dès la conception."

    - icon: "images/icons/arrow-path.svg"
      title: "Maintenance continue."
      text: "Mises à jour, correctifs et évolutions régulières pour garantir la stabilité et la fiabilité de vos projets."

    - icon: "images/icons/finger-print.svg"
      title: "Accès personnalisé."
      text: "Gestion des utilisateurs et des droits sur mesure, pour un contrôle précis et sécurisé."

    - icon: "images/icons/cog-6-tooth.svg"
      title: "Fonctionnalités sur mesure."
      text: "Développement d’APIs et d’outils métiers adaptés à vos besoins spécifiques."

    - icon: "images/icons/server-stack.svg"
      title: "Sauvegardes automatisées."
      text: "Vos données sont protégées grâce à des systèmes de sauvegarde et de restauration fiables."
