# content/site.yaml
layout:
    sections:
        contact: true
        cta: false
        footer: true
        header: true
        hero: true
        logo_cloud: true
        pricing: true
        process: true
        projects: false
        services: true
        stats: false
        testimonials: false
