brand:
    name: "Aleks_DC"

layout:
    sections:
        contact: false
        cta: false
        footer: false
        header: true
        hero: true
        logo_cloud: false
        pricing: false
        process: true
        projects: false
        services: true
        stats: false
        testimonials: false
