name: Deploy to GitHub Pages (Static Export)

on:
    push:
        branches: [ main ]
    pull_request:

permissions:
    contents: write

jobs:
    build-and-export:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: '8.3'
                  tools: composer
                  coverage: none

            - name: Setup Node
              uses: actions/setup-node@v4
              with:
                  node-version: '20'
                  cache: 'npm'

            - name: Install PHP deps (no dev)
              run: composer install --no-dev --prefer-dist --no-progress --no-interaction

            - name: Install JS deps
              run: npm ci

            - name: Build assets (Encore)
              run: npm run build

            - name: Start local PHP server (serveur pour rendre Twig)
              run: php -S 127.0.0.1:8000 -t public > /dev/null 2>&1 &

            - name: Wait for server
              run: |
                  for i in {1..30}; do
                    if curl -sSf http://127.0.0.1:8000/ > /dev/null; then exit 0; fi
                    sleep 1
                  done
                  echo "Server did not start" && exit 1

            - name: Mirror site to docs/ (wget)
              run: |
                  rm -rf docs
                  wget \
                    --mirror \
                    --convert-links \
                    --adjust-extension \
                    --page-requisites \
                    --no-parent \
                    --exclude-directories=/admin,/login \
                    -P docs \
                    http://127.0.0.1:8000/
                  shopt -s dotglob || true
                  mv docs/127.0.0.1:8000/* docs/ || true
                  rm -rf docs/127.0.0.1:8000 || true
                  if [ -f docs/404/index.html ] && [ ! -f docs/404.html ]; then cp docs/404/index.html docs/404.html; fi

            - name: Publish to gh-pages
              uses: peaceiris/actions-gh-pages@v3
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  publish_branch: gh-pages
                  publish_dir: ./docs
                  force_orphan: true
